services:
  overlayer:
    image: ghcr.io/blokadainfo/overlayer:latest
    environment:
      OVERLAY_LOGO_PATH: "/logo.svg"
      OVERLAY_LOGO_HEIGHT: 128
      OVERLAY_LOGO_WIDTH: 128
      OVERLAY_LOGO_ALPHA: 1
      STREAMS_0_SRC: ${STREAMS_0_SRC}
      STREAMS_0_DST: ${STREAMS_0_DST}
      # STREAMS_1_SRC: ${STREAMS_1_SRC}
      # STREAMS_1_DST: ${STREAMS_1_DST}
    volumes:
      - type: bind
        source: ./logo.svg
        target: /logo.svg
        read_only: true
    restart: unless-stopped
